### ISSUE TITLE
support closing/shutting down SSH server

### ISSUE THREAD

**Issue by petergardfjall** [sosedoff/gitkit#16]
Hi, cool library!

I'm writing some git functionality for which I'd like to write unit tests and found this library to be an excellent way of running tests against actual git servers from within the test itself.

However, when running an SSH server, there doesn't seem to be a method of closing a started SSH server (besides killing the process). Would it be possible to add a `Start()/Stop()` method or similar to the `SSH` struct?

**Comment by petergardfjall** [comment]
Would this be okay?
https://github.com/sosedoff/gitkit/pull/17

**Comment by sosedoff** [comment]
#17 merged
