### ISSUE TITLE
git push origin :deleted-branch got error 128

### ISSUE THREAD

**Issue by kevinzheng** [sosedoff/gitkit#18]
It looks like `git show -s --format=%B 0000000000000000000000000000000000000000` cause this error.

**Comment by sosedoff** [comment]
Are you pushing to a deleted branch or deleting a branch?

**Comment by kevinzheng** [comment]
> Are you pushing to a deleted branch or deleting a branch?

I'm pushing a deleted branch

**Comment by sosedoff** [comment]
Do you have the server log i can inspect? I was testing on mac and noticed that ssh server isnt working properly for some reason.

**Comment by sosedoff** [comment]
Ok, i found what's causing this error. You've never mentioned that you're using git receiver with gitkit, so i think the error is valid since you can't really read a message of a deleted branch. 

Here's an example:

```go
func receive(hook *gitkit.HookInfo, tmpPath string) error {
  log.Println("Action:", hook.Action())
  log.Println("Ref:", hook.Ref)
  log.Println("Ref Name:", hook.RefName)
  log.Println("Old revision:", hook.OldRev)
  log.Println("New revision:", hook.NewRev)

  if hook.Action() == "branch.delete" {
    // do something when branch is deleted
    return nil
  }
  
  // .. rest
}
```

**Comment by kevinzheng** [comment]
Sorry I was stupid. I understand now, many thanks!
