### ISSUE TITLE
Getting  403 http error from server

### ISSUE THREAD

**Issue by RamLavi** [sosedoff/gitkit#23]
I'm using gitkit to do git api requests to a local git repository (I'm want to mock githubApi server).
I'm not sure If I'm doing it wrong, this is what I did:

How to recreate: 
1. create the server:
```
// newfakeGithubApi creates a fake interface
func newfakeGithubApi(repoDir string) *mockGithubApi {
	// Configure git service
	service := gitkit.New(gitkit.Config{
		Dir:        repoDir,
		AutoCreate: true,
		AutoHooks:  true,
	})

	// If hooks are set, it will also update all repos with new version of hook scripts.
	err := service.Setup()

	http.Handle("/", service)

	go RunServer()

	return &mockGithubApi{
		gitLocalServer: service,
		repoDir: repoDir,
	}

}

func RunServer() {
	err := http.ListenAndServe(":5000", nil)
}
```

2. I then create the git repo using go-git
```
	repo, err := git.PlainInit(repoDir, false)
	initializeRepo(repo, repoDir) //add some commits and tags
```

3. now I create an http request similar to the one used in the README examples:
```
	url := fmt.Sprintf("http://localhost:5000%s/git/refs", g.repoDir)
	response, err := http.Get(url)
	
	logger.Printf("response = \n%v", response)
```

The response is: 
```
2020/08/06 19:23:09 request: GET localhost:5000/tmp/testedComponent142471760/git/refs
INFO: 2020/08/06 19:23:09 response = 
&{403 Forbidden 403 HTTP/1.1 1 1 map[Content-Length:[10] Content-Type:[text/plain; charset=utf-8] Date:[Thu, 06 Aug 2020 16:23:09 GMT] X-Content-Type-Options:[nosniff]] 0xc0000dd580 10 [] false false map[] 0xc000214000 <nil>}
```

Am I missing something?

**Comment by sosedoff** [comment]
You're getting this error because if this check: https://github.com/sosedoff/gitkit/blob/746d8d7794e10416a12bddd6d7d194fa24fe1fd9/http.go#L67, which looks up what needs to be done in https://github.com/sosedoff/gitkit/blob/746d8d7794e10416a12bddd6d7d194fa24fe1fd9/http.go#L36-L39

**Comment by sosedoff** [comment]
So your `/git/refs` path needs to be `/info/refs`

**Comment by RamLavi** [comment]
using /ingo/refs gives me 404 error
```
2020/08/06 21:12:50 request: GET localhost:5000/tmp/testedComponent788379709/info/refs
INFO: 2020/08/06 21:12:50 response = 
&{404 Not Found 404 HTTP/1.1 1 1 map[Content-Length:[10] Content-Type:[text/plain; charset=utf-8] Date:[Thu, 06 Aug 2020 18:12:50 GMT] X-Content-Type-Options:[nosniff]] 0xc000162200 10 [] false false map[] 0xc0004de100 <nil>}
```

**Comment by RamLavi** [comment]
I think I get it. url needs owner/repo format.. ok I'll try and update you.

**Comment by sosedoff** [comment]
Sounds about right

**Comment by sosedoff** [comment]
@RamLavi did you ever figure this out? If so - please post your findings and close the issue if it's resolved.

**Comment by RamLavi** [comment]
Hi, yes I figured it out, thanks for your input on this :) 
I think we can close this issue
