### ISSUE TITLE
Support for version ssh v2 git

### ISSUE THREAD

**Issue by dexterp** [sosedoff/gitkit#27]
Greetings,

I've been using gitkit as part of my testing for https://github.com/kick-project/kick 

I was wondering if you had any plans to support ssh v2?
At the moment for any ssh based tests, I've been using a private github repository to test private repository access.

I do realise it is a lot of work.

Kind Regards
Dexter

**Comment by sosedoff** [comment]
Perhaps, could you describe the workflow you're using right now with gitkit?
