### ISSUE TITLE
Allow customizing the SSH config

### ISSUE THREAD

**Issue by aryan9600** [sosedoff/gitkit#29]
It'd be helpful if there were a method which allows users to override the [ssh config](https://github.com/sosedoff/gitkit/blob/master/ssh.go#L38). For example, it could be used to specify which key exchange algorithms, that the server should allow for connections.

Happy to work on a PR for the same if agreed upon 😄

**Comment by aryan9600** [comment]
> It'd be helpful if there were a method which allows users to override the [ssh config](https://github.com/sosedoff/gitkit/blob/master/ssh.go#L38). For example, it could be used to specify which key exchange algorithms, that the server should allow for connections
> 
> Happy to work on a PR for the same 😄

**Comment by sosedoff** [comment]
If you have a PR - i can def accept it.
