### ISSUE TITLE
fs abstraction?

### ISSUE THREAD

**Issue by till** [sosedoff/gitkit#31]
Would you be open to using something like billy for fs abstraction? Could be something else as well, I'd like to be able to use different storage so I can run this in a container and not worry about local paths.

**Comment by sosedoff** [comment]
Fs abstraction for what exactly? Also, keep in mind, `gitkit` will shell out to `git` via exec calls

**Comment by till** [comment]
Good to know, I had not looked. Was going to use something like minio to store repositories. But with billy, you can't shell exec.

**Comment by sosedoff** [comment]
Yea `gitkit` only provides services on top of `git` so abstracting things might not be possible.
