### ISSUE TITLE
Proposal: New Feature - On-demand Git Repository Creation

### ISSUE THREAD

**Issue by 0x4139** [sosedoff/gitkit#32]
Curently the library does not have the ability for developers to create on demand new Git repositories, the "autocreate" option takes care of this.

I think it would be useful to expose a method that allows the creation of a repository on demand. "authenticated users creating a repository".

I would like to hear your thoughts about this.

I would submit a pull request.

**Comment by sosedoff** [comment]
This was always supported, take a look at this example:

```go
package main

import (
	"log"
	"net/http"

	"github.com/sosedoff/gitkit"
)

func main() {
	service := gitkit.New(gitkit.Config{
		Dir:        "./repos",
		AutoCreate: true, // <---- here, we will create repos on demand
	})

	if err := service.Setup(); err != nil {
		log.Fatal(err)
	}

	http.Handle("/", service)

	if err := http.ListenAndServe(":5000", nil); err != nil {
		log.Fatal(err)
	}
}

```
