### ISSUE TITLE
Incompatible key type generated by ssh-keygen 7.8

### ISSUE THREAD

**Issue by waveletlet** [sosedoff/gitkit#9]
Running the test ssh server code, I got this error

    2018/09/15 15:15:42 ssh: unhandled key type

The problem seems to be ssh.ParsePrivateKey is expecting a PEM encoded private key, and the version of ssh-keygen I'm running (7.8) has the following change:

> ssh-keygen(1): write OpenSSH format private keys by default
   instead of using OpenSSL's PEM format. ... If necessary, it is possible to write
   old PEM-style keys by adding "-m PEM" to ssh-keygen's arguments
   when generating or updating a key.

**Comment by sosedoff** [comment]
Fixed in master
